### ISSUE TITLE
"Show all" link on right-side blog index not clickable on short posts

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#47] opened 2020-05-21 13:14 UTC
When a blog post body is short and the post index right side of a blog post page must be scrolled to the reach it, the "Show all" link displays but is not clickable. This is not a problem on longer blog  post pages when the "Show all: link scrolls farther up the page.

The link should be seen and clickable regardless of the length of the blog post.

An example is here:

https://www.ietf.org/blog/ietf108-online/
Attached is a screenshot.

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/5347540/82562308-f6dc4900-9b42-11ea-9f13-ef41036c8a65.png">

**Comment by rjsparks** [comment] 2020-05-21 16:31
This is a duplicate of #24.
I'm going to close this one. The mention here will let anyone working on #24 find the screenshot.

**Closed by rjsparks** 2020-05-21 16:31 UTC
Labels: page-template
