### ISSUE TITLE
reduce table padding

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#85] opened 2021-04-06 19:56 UTC
current padding is:

   .block-table__container td, .block-table__container th, .block-table td, .block-table th {
       padding: 20px;
   }

it might be reduced to something like:

   .block-table__container td, .block-table__container th, .block-table td, .block-table th {
       padding: 10px;
   }

**Comment by JayDaley** [comment] 2021-06-17 03:48
Duplicate of #76

**Comment by JayDaley** [comment] 2021-06-30 19:43
closed as duplicate

**Closed by JayDaley** 2021-06-30 19:43 UTC
